name: deploy web

on:
  release:
    types:
      - published
  pull_request:
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  deploy_website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Build
        run: |
          cd web
          yarn && yarn build:online

      - name: Publish Package
        run: |
          cd web
          yarn publish --non-interactive --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SMS_TOKEN }}
