name: deploy web

on:
  release:
    types:
      - published
  pull_request:
    paths:
      - 'web/**'
  workflow_dispatch:

jobs:
  deploy_website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Build
        run: |
          cd web
          yarn && yarn build:online

      - name: Archive Build Artifacts
        run: |
          cd web
          # 假设构建输出在 'dist' 目录下，您可以根据实际情况修改
          tar -czf build-artifacts.tar.gz dist
        # 这里假设 dist 是构建输出文件夹
		
	  - name: Upload Build Artifacts
		uses: actions/upload-artifact@v4
		with:
		  name: build-artifacts
		  path: web/build-artifacts.tar.gz
